### ISSUE TITLE
[BUG]: BfA LFRs at Kiku are not correct

### ISSUE THREAD

**Issue by KyrosKrane** [HizurosWoWAddOns/LFR_of_the_past#4]
### WoW client

WoW Retail

### What happened?

The entries for Battle for Azeroth LFRs at Kiku in Boralus are not correct.

Several raids don't align; for example, mousing over "The Waking Dream 0/2 Ny'alotha" shows the entries for Vision of Destiny. Additionally, the last three lines don't appear to be parsed.

![image](https://user-images.githubusercontent.com/458727/233818761-6bdd9bb0-0efb-4de4-a41d-ddea7bdf4d9a.png)

### Other addons?

Tested with only LFR of the Past loaded.

**Comment by KyrosKrane** [comment]
I tested clicking on the LFR[OTP] entry for "The Waking Dream" and it actually queued me for Vision of Destiny. Clicking on the unparsed line for The Waking Dream correctly queued me for that wing.

**Comment by Taizunz** [comment]
Until this gets fixed just rely on the tooltip text on the right side to select the correct one.

It's the same issue on the Pandaria LFR NPC.
![image](https://user-images.githubusercontent.com/15648000/233831954-d22a95df-0668-4b37-832f-f19fd0774f8d.png)

**Comment by hizuro** [comment]
Version 1.4.4-release should fix list of lfr wings from all npc.
