### ISSUE TITLE
[BUG]: Might of the Alliance (BFA Dazar'alor raid part 3) missing Jaina

### ISSUE THREAD

**Issue by KyrosKrane** [HizurosWoWAddOns/LFR_of_the_past#5]
### WoW client

WoW Retail

### What happened?

When mousing over the Might of the Alliance raid at Kiku in Boralus, it only shows the first two bosses - Mekkatorque and Blockade. Jaina is missing.

![image](https://github.com/HizurosWoWAddOns/LFR_of_the_past/assets/458727/f9f9a794-964c-474f-a264-c3f355c981b3)

### Lua Error Message?

```lua
None.
```

### Other addons?

Tested with only LFR OTP, Buggrabber, and Bugsack loaded.

**Comment by Taizunz** [comment]
Same on the Horde side.

**Comment by hizuro** [comment]
Thanks for reporting.
Update coming soon.

**Comment by KyrosKrane** [comment]
Confirmed this is fixed.
